import { supabase } from "@/lib/supabase";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Calendar, Clock, ArrowRight, Sparkles, Zap, ChevronRight } from "lucide-react";
import Link from "next/link";
import Navbar from "@/components/layout/Navbar";

export const dynamic = 'force-dynamic';

export default async function BlogPage() {
  const { data: posts, error } = await supabase
    .from('blog_posts')
    .select('*')
    .order('published_at', { ascending: false });

  return (
    <div className="min-h-screen bg-[#0a0f1e] text-white selection:bg-primary selection:text-background">
      <Navbar />
      
      <main className="pt-32 pb-20 px-4">
        <div className="max-w-7xl mx-auto space-y-16">
          <header className="text-center space-y-4">
            <div className="flex justify-center">
               <span className="inline-flex items-center px-4 py-1.5 rounded-full border border-primary/20 bg-primary/5 text-primary text-[10px] font-mono font-bold tracking-widest uppercase mb-4">
                <Sparkles className="w-3 h-3 mr-2" /> 100% AI Generated Insights
              </span>
            </div>
            <h1 className="text-5xl md:text-7xl font-bold font-outfit tracking-tight">The EduVerse <span className="text-primary italic">Journal</span></h1>
            <p className="text-muted-foreground text-lg max-w-2xl mx-auto font-mono text-sm leading-relaxed">
              Global education insights generated by our autonomous AI agents to guide your study-abroad success.
            </p>
          </header>

          {/* Featured Post (if exists) */}
          {posts && posts[0] && (
            <Link href={`/blog/${posts[0].slug}`}>
              <Card className="bg-[#111827] border-white/10 hover:border-primary/50 transition-all overflow-hidden group shadow-2xl">
                 <div className="grid lg:grid-cols-2">
                    <div className="h-64 lg:h-full bg-gradient-to-br from-primary/20 via-primary/5 to-transparent relative">
                       <div className="absolute inset-0 flex items-center justify-center opacity-10 group-hover:opacity-20 transition-opacity">
                          <Zap className="w-64 h-64 text-primary" />
                       </div>
                    </div>
                    <CardContent className="p-8 lg:p-12 space-y-6">
                       <div className="flex items-center space-x-4 text-xs font-mono text-primary font-bold">
                          <span className="flex items-center"><Calendar className="w-3.5 h-3.5 mr-1.5" /> {new Date(posts[0].published_at).toLocaleDateString()}</span>
                          <span className="flex items-center"><Clock className="w-3.5 h-3.5 mr-1.5" /> 8 min read</span>
                       </div>
                       <h2 className="text-3xl lg:text-4xl font-bold font-outfit group-hover:text-primary transition-colors">{posts[0].title}</h2>
                       <p className="text-muted-foreground leading-relaxed line-clamp-3">
                          {posts[0].meta_description || posts[0].content.slice(0, 200) + '...'}
                       </p>
                       <div className="pt-4">
                          <Button className="h-12 px-6 bg-primary text-background font-bold rounded-lg group-hover:scale-105 transition-transform">
                             Read Full Article <ArrowRight className="ml-2 w-4 h-4" />
                          </Button>
                       </div>
                    </CardContent>
                 </div>
              </Card>
            </Link>
          )}

          {/* Grid Feed */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {posts?.slice(1).map((post: any) => (
              <Link key={post.id} href={`/blog/${post.slug}`}>
                <Card className="bg-[#111827] border-white/10 h-full hover:border-primary/50 hover:bg-white/[0.02] transition-all group shadow-xl">
                  <CardContent className="p-6 space-y-4">
                    <div className="flex items-center justify-between text-[10px] font-mono text-muted-foreground uppercase tracking-widest">
                       <span className="flex items-center"><Calendar className="w-3 h-3 mr-2" /> {new Date(post.published_at).toLocaleDateString()}</span>
                       <span className="flex items-center text-primary font-bold italic">Expert Post</span>
                    </div>
                    <h3 className="text-xl font-bold font-outfit line-clamp-2 leading-tight group-hover:text-primary transition-colors">{post.title}</h3>
                    <p className="text-xs text-muted-foreground line-clamp-3 leading-relaxed">
                      {post.meta_description}
                    </p>
                    <div className="pt-4 flex items-center text-primary text-[10px] font-mono font-bold uppercase tracking-wider opacity-0 group-hover:opacity-100 transition-all -translate-x-2 group-hover:translate-x-0">
                       Read More <ChevronRight className="ml-1 w-3 h-3" />
                    </div>
                  </CardContent>
                </Card>
              </Link>
            ))}
          </div>

          {!posts?.length && (
            <div className="text-center py-20 border border-dashed border-white/10 rounded-3xl opacity-30">
               <Zap className="w-12 h-12 mx-auto mb-4 text-primary" />
               <p className="font-mono text-xs uppercase tracking-widest">Growth Engine generating first insights...</p>
            </div>
          )}
        </div>
      </main>

      <footer className="py-20 border-t border-white/10 bg-black/20">
        <div className="max-w-7xl mx-auto px-4 text-center space-y-8">
           <h4 className="text-2xl font-bold font-outfit">Ready to start your own story?</h4>
           <p className="text-muted-foreground max-w-lg mx-auto">Use our free AI tools to predict your admission odds and plan your finances today.</p>
           <div className="flex justify-center space-x-4">
              <Link href="/signup">
                 <Button className="h-12 px-8 bg-primary text-black font-bold rounded-xl">Get Started Free</Button>
              </Link>
           </div>
        </div>
      </footer>
    </div>
  );
}
