export const DEMO_PROFILE = {
  id: 'demo-user',
  name: 'Arjun Sharma',
  email: 'demo@eduverse.app',
  degree: 'B.Tech/B.E.',
  field: 'Computer Science & Engineering',
  gpa: 8.4,
  gre: 318,
  ielts: 7.5,
  workExp: 1,
  workDetails: '6-month internship at Infosys as a backend developer (Java, Spring Boot)',
  targetCountries: ['USA', 'Canada', 'Germany'],
  targetPrograms: ['MS Computer Science', 'MS Software Engineering', 'MS Artificial Intelligence'],
  budget: 55000,
  careerGoal: 'Work as an AI/ML engineer at a top tech company for 5 years, then return to India to build a startup in the healthcare AI space',
  xp_points: 340,
  streak_days: 3,
  graduation_year: 2024,
  onboarding_complete: true,
  current_degree: 'B.Tech/B.E.', 
  target_countries: ['USA', 'Canada', 'Germany'],
};

export const DEMO_SHORTLIST = [
  {
    id: 'demo-sl-1',
    university_name: 'University of California, San Diego',
    program: 'MS Computer Science',
    country: 'USA',
    tuition_usd: 29000,
    ranking: '#34 US News CS',
    fit_score: 82,
    application_deadline: new Date(Date.now() + 47 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'preparing',
    admission_probability: 68,
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-sl-2',
    university_name: 'University of Toronto',
    program: 'MEng Electrical & Computer Engineering',
    country: 'Canada',
    tuition_usd: 22000,
    ranking: '#18 QS Canada',
    fit_score: 78,
    application_deadline: new Date(Date.now() + 62 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'researching',
    admission_probability: 74,
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-sl-3',
    university_name: 'TU Munich',
    program: 'MSc Informatics',
    country: 'Germany',
    tuition_usd: 2500,
    ranking: '#50 QS Global',
    fit_score: 71,
    application_deadline: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'applied',
    admission_probability: 55,
    created_at: new Date().toISOString(),
  },
];
